name: Integration

on:
  push:

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: ./
        with:
          config: testdata/path/to/config.yml
